MB-8979 remove "please check your username..." suffix from unrelated
... error messages.

If the creadentials are incorrect the following error will be printed
by restclient code:
ERROR: unable to access the REST API - please check your username (-u) and password (-p)

Adding the above suffix to other error messages is very confusing
because getting 400 from the rest API already means that that the
auth was successful

Change-Id: I48c3f2306943cae9154b1a668686d5eaa854794a
Reviewed-on: http://review.couchbase.org/35983
Tested-by: Artem Stemkovski <artem@couchbase.com>
Reviewed-by: Bin Cui <bin.cui@gmail.com>